<a href="https://colab.research.google.com/github/danilo-uea/RNA-2021.1-AA2.1/blob/main/RNA_AA_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Redes Neurais Artificiais - Atividade Avaliativa 2.1
> Criado por: Danilo Frazão, Rafael Aragão Morais & Yasser Tuma




In [45]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt
from prettytable import PrettyTable

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


###Importando os dados

> O arquivo com os dados está armazenado em uma pasta do Google Drive, como é um arquivo em binario, iremos utilizar a biblioteca numpy para extrair os dados.



In [5]:
def import_data(path):
  dt = np.dtype(float)
  arq = np.fromfile(path, dtype=dt)

  ret = np.empty((0, 3), float)

  for i in range(0, len(arq), 3):
    linha = np.array([[arq[i], arq[i+1], arq[i+2]]])
    ret = np.append(ret, linha, axis=0)

  return ret


In [6]:
drivePath = "/content/drive/My Drive/Colab Notebooks/RNA/data/dataAll.txt"
data_All = import_data(drivePath)
data_All

array([[-363.7884,  244.1423,    0.    ],
       [ 328.7572, -256.7658,    1.    ],
       [-164.9827,  613.2164,    0.    ],
       ...,
       [ 872.4311,  669.1192,    1.    ],
       [ 822.6894, -702.6489,    1.    ],
       [-140.147 ,  734.0983,    0.    ]])

##Perceptron


> As funções abaixo compõem o treinamento, ajuste dos pesos, de um Perceptron



In [7]:
def activationFunction(u, teta):
  if(u >= teta):
    return 1
  else:
    return 0

In [8]:
def sumFunction(X, W):
  sum = 0
  for x,w in zip(X,W):
    sum += x*w
  return sum

In [9]:
def weightAdjustment(W, n, e, X):
  delta = np.dot((n*e), X)
  new_weight = np.add(W, delta);
  return new_weight

In [10]:
def addBias(inputData, bias):
  nd= np.insert(inputData, 2, bias, axis=1)
  return nd


In [11]:
def epoch(inputData, W, n, teta):
  adjusts = 0;
  weights = []
  for idx, row in enumerate(inputData):
    sum = sumFunction(row[:-1], W)
    yp = activationFunction(sum, teta)
    if(row[-1] != yp):
      adjusts += 1;
      W = weightAdjustment(W, n, (row[-1] - yp), row[:-1])
      weights.append((idx, W))
  return (adjusts, weights, W)



In [12]:
def perceptronLearning(inputData, W, maxEpoch, n, teta):
  epochCount = 0
  adjustCount = 0
  adjust = True
  while(adjust):
    epochCount += 1
    (numAdjusts, oldWeights, W) = epoch(inputData, W, n, teta)

    print("\nNumero de epocas: " + str(epochCount))
    print("Numero de ajustes: " + str(numAdjusts))
    
    adjustCount += numAdjusts
    
    if(numAdjusts == 0):
      adjust = False #nao houve alteracoes nos valores dos pesos
      print("Os pesos foram ajustados")
    else:
      print("Pesos antigos e a linha em que foram alterados")
      for weight in oldWeights:
        print(weight[1], " - linha: ", weight[0])
      if(epochCount == maxEpoch):
        print("O limite maximo de epocas foi alcancado e nao foi possivel ajustar os pessos corretamente")
        break

  print("\nPesos finais: ", W)
  print("Numero total de epocas: " + str(epochCount))
  print("Numero total de ajustes: " + str(adjustCount))
  return (W, epochCount, adjustCount)


In [19]:
def perceptronTest(W, Xt, Yt, teta):
  tp = []
  tn = []
  fp = []
  fn = [] #true positive, true negative, false positive, false negative
  for row, yr in zip(Xt, Yt):
    sum = sumFunction(row[:-1], W)
    yp = activationFunction(sum, teta)
    result = (row, yp, yr)
    if(yp == yr):
      if(yp == 0):
        tp.append(result)
      else:
        tn.append(result)
    else:
      if(yp == 0):
        fp.append(result)
      else:
        fn.append(result)
  return (tp, tn, fp, fn)


## Parte I - Resolvendo um problema linearmente separavel



> Para esta parte, iremos utilizar o arquivo dataAll.txt;

> O neurônio perceptron terá as seguintes características:

*   Função de ativação degrau com limiar = 0,

*   Taxa de aprendizado = 0.1,

*   Os pesos das entradas inicialmente serão valores aleatórios no intervalo de -0.5 e 0.5 .








In [14]:
n_DataAll = 0.1 # taxa de aprendizado
teta_DataAll = 0 #degrau
w_DataAll = np.random.uniform(-0.5, 0.5, 3) #min, max, numero_de_valores
print("Vetor de pesos iniciais: ")
print(w_DataAll)
data_All = addBias(data_All, 1)
print("\n\nDados de entrada com o vies: \n [x1, x2, vies, y] \n")
data_All

Vetor de pesos iniciais: 
[ 0.39292903 -0.21494394 -0.04777283]


Dados de entrada com o vies: 
 [x1, x2, vies, y] 



array([[-363.7884,  244.1423,    1.    ,    0.    ],
       [ 328.7572, -256.7658,    1.    ,    1.    ],
       [-164.9827,  613.2164,    1.    ,    0.    ],
       ...,
       [ 872.4311,  669.1192,    1.    ,    1.    ],
       [ 822.6894, -702.6489,    1.    ,    1.    ],
       [-140.147 ,  734.0983,    1.    ,    0.    ]])

In [26]:
(finalWeights, num_epochs, num_adjusts) = perceptronLearning(data_All, w_DataAll, 0, n_DataAll, teta_DataAll)


Numero de epocas: 1
Numero de ajustes: 48
Pesos antigos e a linha em que foram alterados
[-53.26612097 -76.71069394  -0.14777283]  - linha:  3
[ 19.52989903 -40.88113394  -0.04777283]  - linha:  7
[1.02128599e+02 3.89746961e+01 5.22271682e-02]  - linha:  18
[ 1.07974359e+02 -3.93198939e+01 -4.77728318e-02]  - linha:  26
[  67.96544903 -117.21258394   -0.14777283]  - linha:  31
[126.40836903 -75.63230394  -0.24777283]  - linha:  41
[  73.44830903 -132.50176394   -0.14777283]  - linha:  45
[133.00782903 -82.37943394  -0.24777283]  - linha:  47
[ 8.74831990e+01 -1.48015364e+02 -1.47772832e-01]  - linha:  71
[ 101.82162903 -138.62914394   -0.24777283]  - linha:  104
[192.53748903 -63.91582394  -0.34777283]  - linha:  107
[ 134.75649903 -124.22397394   -0.24777283]  - linha:  110
[ 8.48466790e+01 -1.75484404e+02 -1.47772832e-01]  - linha:  178
[ 1.12670409e+02 -1.57429484e+02 -4.77728318e-02]  - linha:  197
[ 1.40133999e+02 -1.36573134e+02  5.22271682e-02]  - linha:  220
[ 7.12783190e+01 -

In [ ]:
#grafico
def plotLine(inputData, W):
  red = []
  blue = []
  for row in inputData:
    if(row[-1] == 0.0):
      red.append((row[0], row[1]))
    else:
      blue.append((row[0], row[1]))

def plotLine(inputData, W):
  h = []
  v = []
  for row in inputData:
    h.append(row[0])
    v.append(row[1])
    if(row[-1] == 0):
     plt.scatter(row[0], row[1], color='red')
    else:
      plt.scatter(row[0], row[1], color='blue')
  plt.plot(h , v, 'o')

plotLine(data_All, finalWeights)

In [ ]:
#plt.plot(, y, 'o', color='black');
data_All[0]

array([-363.7884,  244.1423,    1.    ,    0.    ])

# Parte 2 - Experimentacao

> Para esta parte, iremos utilizar o arquivo data0.txt;

> O neurônio perceptron terá as seguintes características:

*   Função de ativação degrau com limiar = 0,

*   Taxa de aprendizado = {0.4, 0.1, 0.01},

*   Os pesos das entradas inicialmente serão valores aleatórios no intervalo de {(-100,100) (-0.5 e 0.5)} ,

*   Para cada combinação entre os possiveis valores da taxa de aprendizado e do intervalo inicial dos pesos, será realizada 10 interações.










In [50]:
drivePath2 = "/content/drive/My Drive/Colab Notebooks/RNA/data/data0.txt"
data0 = import_data(drivePath2)
data0

array([[-0.00149369, -0.03581784,  0.        ],
       [ 0.01234945,  0.10249524,  0.        ],
       [ 0.13954598,  0.05607083,  0.        ],
       ...,
       [ 0.95751872,  1.0035204 ,  1.        ],
       [ 0.97981588,  1.00949493,  1.        ],
       [ 1.02021556,  0.86533059,  1.        ]])

In [49]:
def perceptronLearningPart2(inputData, W, maxEpoch, n, teta):
  epochCount = 0
  adjustCount = 0
  adjust = True
  while(adjust):
    epochCount += 1
    (numAdjusts, oldWeights, W) = epoch(inputData, W, n, teta)
    
    adjustCount += numAdjusts
    
    if(numAdjusts == 0):
      adjust = False #nao houve alteracoes nos valores dos pesos
    else:
        if(epochCount == maxEpoch):
          break
  return (W, epochCount, adjustCount)


In [47]:
def iteration(inputData, w_index, n, teta):
  minEpochs = 0
  adjusts = []
  inputData = addBias(inputData, 1)

  for i in range(10):
    if(w_index == 0):
      W = np.random.uniform(-100, 100, 3)
    else:
      W = np.random.uniform(-0.5, 0.5, 3)
    
    (finalWeights, num_epochs, num_adjusts) = perceptronLearningPart2(inputData, W, 0, n, teta)

    if(minEpochs > num_epochs or not adjusts):
      minEpochs = num_epochs

    adjusts.append(num_adjusts)

  return ((sum(adjusts) / 10), np.std(adjusts), minEpochs)


In [51]:
PT = PrettyTable()

first_row = iteration(data0, 0, 0.4, 0)
second_row = iteration(data0, 1, 0.4, 0)
third_row = iteration(data0, 0, 0.1, 0)
fourth_row = iteration(data0, 1, 0.1, 0)
fifth_row = iteration(data0, 0, 0.01, 0)
sixth_row = iteration(data0, 1, 0.01, 0)

PT.field_names = ["Taxa de aprendizado", "Intervalo de pesos", "Media do numero de ajustes", "Desvio padrao do numero de ajustes", "Menor numero de epocas"]
PT.add_row(["n=0.4", "{-0.5, 0.5}", first_row[0], first_row[1], first_row[2]])
PT.add_row(["n=0.4", "{-100, 100}", second_row[0], second_row[1], second_row[2]])
PT.add_row(["n=0.1", "{-0.5, 0.5}", third_row[0], third_row[1], third_row[2]])
PT.add_row(["n=0.1", "{-100, 100}", fourth_row[0], fourth_row[1], fourth_row[2]])
PT.add_row(["n=0.01", "{-0.5, 0.5}", fifth_row[0], fifth_row[1], fifth_row[2]])
PT.add_row(["n=0.01", "{-100, 100}", sixth_row[0], sixth_row[1], sixth_row[2]])

print(PT)

+---------------------+--------------------+----------------------------+------------------------------------+------------------------+
| Taxa de aprendizado | Intervalo de pesos | Media do numero de ajustes | Desvio padrao do numero de ajustes | Menor numero de epocas |
+---------------------+--------------------+----------------------------+------------------------------------+------------------------+
|        n=0.4        |    {-0.5, 0.5}     |           266.0            |         191.10102040543896         |           3            |
|        n=0.4        |    {-100, 100}     |            9.7             |         3.3778691508109073         |           3            |
|        n=0.1        |    {-0.5, 0.5}     |           1235.6           |          623.245248678239          |           9            |
|        n=0.1        |    {-100, 100}     |            9.7             |         4.313930922024598          |           2            |
|        n=0.01       |    {-0.5, 0.5}     |    

# Comentar sobre a tabela

# Parte 3 - Validacao Houlout em Problema Nao-Linearmente Separavel

> Para esta parte, iremos utilizar o arquivo dataHoldout.txt;

> O neurônio perceptron terá as seguintes características:











In [75]:
drivePath3 = "/content/drive/My Drive/Colab Notebooks/RNA/data/dataHoldout.txt"
dataHoldout = import_data(drivePath3)
dataHoldout

array([[-0.29322959, -0.09065359,  1.        ],
       [ 0.07988839,  0.21101297,  1.        ],
       [-0.07825563, -0.08083512,  1.        ],
       ...,
       [ 0.65980493,  1.05876739,  0.        ],
       [ 1.09867123,  0.87404891,  0.        ],
       [ 0.72930655,  0.93224271,  0.        ]])

In [76]:
# embaralhar os dados
random.shuffle(dataHoldout)

print(dataHoldout)

[[-0.29322959 -0.09065359  1.        ]
 [-0.29322959 -0.09065359  1.        ]
 [ 0.07988839  0.21101297  1.        ]
 ...
 [ 1.02015246  1.33204147  0.        ]
 [ 0.17537603  0.17826557  1.        ]
 [-0.13180539  0.94778105  0.        ]]


In [77]:
n_DataHouldout = 0.2 # taxa de aprendizado
teta_DataHouldout = 0 #degrau
w_DataHouldout = np.random.uniform(-0.5, 0.5, 3) #min, max, numero_de_valores
print("Vetor de pesos iniciais: ")
print(w_DataHouldout)
dataHoldout = addBias(dataHoldout, 1)
print("\n\nDados de entrada com o vies: \n [x1, x2, vies, y] \n")
dataHoldout



Vetor de pesos iniciais: 
[ 0.18818413 -0.29226627 -0.08924086]


Dados de entrada com o vies: 
 [x1, x2, vies, y] 



array([[-0.29322959, -0.09065359,  1.        ,  1.        ],
       [-0.29322959, -0.09065359,  1.        ,  1.        ],
       [ 0.07988839,  0.21101297,  1.        ,  1.        ],
       ...,
       [ 1.02015246,  1.33204147,  1.        ,  0.        ],
       [ 0.17537603,  0.17826557,  1.        ,  1.        ],
       [-0.13180539,  0.94778105,  1.        ,  0.        ]])

In [78]:
lenDataHouldout = len(dataHoldout)
print("Tamanho do dataset: " + str(lenDataHouldout))
sliceIndex = len(dataHoldout)*0.7
print("Quantidade de elementos que vao compor o conjunto de treino (70\%): " + str(sliceIndex))
print("Quantidade de elementos que vao compor o conjunto de teste (30\%): " + str(lenDataHouldout - sliceIndex))

dataHoldout_train = dataHoldout[slice(0, int(sliceIndex))]
dataHoldout_test = dataHoldout[slice(int(sliceIndex), int(lenDataHouldout))]

print("\nConjunto de treino: \n")
print(dataHoldout_train)
print("\nConjunto de teste: \n")
print(dataHoldout_test)

Tamanho do dataset: 800
Quantidade de elementos que vao compor o conjunto de treino (70\%): 560.0
Quantidade de elementos que vao compor o conjunto de teste (30\%): 240.0

Conjunto de treino: 

[[-0.29322959 -0.09065359  1.          1.        ]
 [-0.29322959 -0.09065359  1.          1.        ]
 [ 0.07988839  0.21101297  1.          1.        ]
 ...
 [-0.21748562  0.03151915  1.          1.        ]
 [-0.00714871  1.11139215  1.          0.        ]
 [ 0.17425036  0.83570736  1.          0.        ]]

Conjunto de teste: 

[[ 2.48791156e-01  9.65268451e-01  1.00000000e+00  0.00000000e+00]
 [ 5.78474894e-01 -5.75790426e-02  1.00000000e+00  0.00000000e+00]
 [ 1.10627429e+00  9.65101337e-02  1.00000000e+00  0.00000000e+00]
 [ 3.67543709e-01  9.08209929e-03  1.00000000e+00  1.00000000e+00]
 [ 8.94821800e-02 -2.22426266e-01  1.00000000e+00  1.00000000e+00]
 [ 7.79238720e-01 -3.37379197e-01  1.00000000e+00  0.00000000e+00]
 [-5.47258046e-02 -1.11312138e-01  1.00000000e+00  1.00000000e+00]
 [ 

In [79]:
(houldoutWeights, epochsHouldout, adjustsHouldout) = perceptronLearning(dataHoldout_train, w_DataHouldout, 100, n_DataHouldout, teta_DataHouldout)


Numero de epocas: 1
Numero de ajustes: 30
Pesos antigos e a linha em que foram alterados
[ 0.12953822 -0.31039699  0.11075914]  - linha:  0
[ 0.10875518 -0.2411206   0.31075914]  - linha:  24
[ 0.09779169 -0.44480963  0.11075914]  - linha:  235
[ 0.15058    -0.37930787  0.31075914]  - linha:  260
[ 0.14619477 -0.53559365  0.11075914]  - linha:  276
[ 0.21140876 -0.46920104  0.31075914]  - linha:  278
[ 0.18229821 -0.61114259  0.11075914]  - linha:  287
[ 0.20633898 -0.52916297  0.31075914]  - linha:  299
[ 0.13826281 -0.67077204  0.11075914]  - linha:  367
[ 0.15774916 -0.62276759  0.31075914]  - linha:  372
[-0.06952521 -0.60283103  0.11075914]  - linha:  429
[-0.25847306 -0.57654056 -0.08924086]  - linha:  430
[-0.20170733 -0.57791897  0.11075914]  - linha:  431
[-0.36900802 -0.55592286 -0.08924086]  - linha:  440
[-0.42285722 -0.49002184  0.11075914]  - linha:  444
[-0.40728654 -0.4405832   0.31075914]  - linha:  451
[-0.34337726 -0.60547681  0.11075914]  - linha:  460
[-0.34130549

In [80]:
(tp, tn, fp, fn) = perceptronTest(houldoutWeights, dataHoldout_test, dataHoldout_test[:,3], teta_DataHouldout)

(tp, tn, fp, fn) = (len(tp), len(tn), len(fp), len(fn))

confusionMatrix = PrettyTable()
confusionMatrix.field_names= ["","Positivo", "Negativo"]
confusionMatrix.add_row(["Verdadeiro", tp, tn])
confusionMatrix.add_row(["Falso", fp, fn])

print(confusionMatrix)

+------------+----------+----------+
|            | Positivo | Negativo |
+------------+----------+----------+
| Verdadeiro |   159    |    75    |
|   Falso    |    3     |    3     |
+------------+----------+----------+


In [83]:
#acuracia
accuracy = (tp + tn) / (tp + tn + fp + fn)
#precisao
precision = tp / (tp + fp)

# revocacao
recall = tp / (tp + fn)

#f-score
FScore = 2 * ((precision * recall) / (precision + recall))

metrics = PrettyTable()
metrics.field_names= ["Metrica", "Valor"]
metrics.add_row(["Acuracia", accuracy])
metrics.add_row(["Precisao", precision])
metrics.add_row(["Revocacao", recall])
metrics.add_row(["F-Score", FScore])
print(metrics)

+-----------+--------------------+
|  Metrica  |       Valor        |
+-----------+--------------------+
|  Acuracia |       0.975        |
|  Precisao | 0.9814814814814815 |
| Revocacao | 0.9814814814814815 |
|  F-Score  | 0.9814814814814815 |
+-----------+--------------------+


In [ ]:
n = 0.1 #Taxa de aprendizado
teta = 0 #Degrau usado na função de ativação
w = np.random.uniform(-0.5, 0.5, (1, 3)) #Vetor de pesos inicial
print("Vetor inicial de pesos: {}\n".format(w[0]))
 
def funcao(u): #Função de ativação
  if(u >= teta):
    return 1
  else:
    return 0
 
i = 0
ult_indice = len(dados_All) - 1
encerrar = True
qtd_epocas = 0
total_ajustes = 0
 
while i <= ult_indice:
  
  if (i == 0): #Verifica a a quantidade de épocas
    qtd_epocas += 1
    print('Época: {}'.format(qtd_epocas))
  
  linha = dados_All[i]
  yd = linha[2]
  x = np.array([-1, linha[0], linha[1]])
 
  u = 0
  for j in range(3):
    u += (x[j] * w[-1][j])
 
  y = funcao(u) #Chama a função de ativação
  e = yd - y #Erro
 
  if (e != 0): #Há necessidade de aprendizagem
    print('Ajuste do peso: {} -> Exemplo: {}'.format(w[-1], i + 1))
    peso_novo = np.array([w[-1] + ((n * e) * x)]) #Delta
    w = np.append(w, peso_novo, axis=0) #Começa a próxima época
    encerrar = False
    total_ajustes += 1
 
  if (ult_indice == i): #Última linha
    print('Número de ajustes: {}'.format(total_ajustes))
    print('Vetor de pesos: ', w[-1])
    print('\n')
    if (encerrar == False):
      total_ajustes = 0
      encerrar = True
      i = -1 #Vai para o começo do array de dados
 
  i += 1
 
print('Total de ajustes: ', len(w) - 1)
print('Total de épocas: ', qtd_epocas)

Vetor inicial de pesos: [-0.01377581 -0.25390031 -0.20273453]

Época: 1
Ajuste do peso: [-0.01377581 -0.25390031 -0.20273453] -> Exemplo: 1
Ajuste do peso: [  0.08622419  36.12493969 -24.61696453] -> Exemplo: 4
Ajuste do peso: [   0.18622419  -17.53411031 -101.11271453] -> Exemplo: 8
Ajuste do peso: [  0.08622419  55.26190969 -65.28315453] -> Exemplo: 19
Ajuste do peso: [-1.37758150e-02  1.37860610e+02  1.45726755e+01] -> Exemplo: 27
Ajuste do peso: [ 8.62241850e-02  1.43706370e+02 -6.37219145e+01] -> Exemplo: 32
Ajuste do peso: [   0.18622419  103.69745969 -141.61460453] -> Exemplo: 44
Ajuste do peso: [  0.28622419 157.36726969 -92.52233453] -> Exemplo: 46
Ajuste do peso: [   0.18622419  104.40720969 -149.39179453] -> Exemplo: 48
Ajuste do peso: [  0.28622419 163.96672969 -99.26946453] -> Exemplo: 72
Ajuste do peso: [   0.18622419  118.44209969 -164.90539453] -> Exemplo: 108
Ajuste do peso: [  0.28622419 209.15795969 -90.19207453] -> Exemplo: 111
Ajuste do peso: [   0.18622419  151.37