<a href="https://colab.research.google.com/github/danilo-uea/RNA-2021.1-AA2.1/blob/main/RNA_AA_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Redes Neurais Artificiais - Atividade Avaliativa 2.1
> Criado por: Danilo Frazão, Rafael Aragão Morais & Yasser Tuma




In [61]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt

In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Parte I - Resolvendo um problema linearmente separavel



> Para esta parte, iremos utilizar o arquivo dataAll.txt;

> O neurônio perceptron terá as seguintes características:

*   Função de ativação degrau com limiar = 0,

*   Taxa de aprendizado = 0.1,

*   Os pesos das entradas inicialmente serão valores aleatórios no intervalo de -0.5 e 0.5 .








###Importando os dados

> O arquivo com os dados está armazenado em uma pasta do Google Drive, como é um arquivo em binario, iremos utilizar a biblioteca numpy para extrair os dados.



In [63]:
def import_data(path):
  dt = np.dtype(float)
  arq = np.fromfile(path, dtype=dt)

  ret = np.empty((0, 3), float)

  for i in range(0, len(arq), 3):
    linha = np.array([[arq[i], arq[i+1], arq[i+2]]])
    ret = np.append(ret, linha, axis=0)

  return ret


In [64]:
drivePath = "/content/drive/My Drive/Colab Notebooks/RNA/data/dataAll.txt"
data_All = import_data(drivePath)
data_All

array([[-363.7884,  244.1423,    0.    ],
       [ 328.7572, -256.7658,    1.    ],
       [-164.9827,  613.2164,    0.    ],
       ...,
       [ 872.4311,  669.1192,    1.    ],
       [ 822.6894, -702.6489,    1.    ],
       [-140.147 ,  734.0983,    0.    ]])

##Perceptron
Algoritmo de treinamento do perceptron

In [65]:
def activationFunction(u):
  if(u >= 0):
    return 1
  else:
    return 0

In [66]:
def sumFunction(X, W):
  sum = 0
  for x,w in zip(X,W):
    sum += x*w
  return sum

In [67]:
def weightAdjustment(W, n, e, X):
  delta = np.dot((n*e), X)
  new_weight = np.add(W, delta);
  return new_weight

In [74]:
def epoch(inputData, W, n):
  adjusts = 0;
  weights = []
  for row in inputData:
    sum = sumFunction(row[:-1], W)
    yp = activationFunction(sum)
    if(row[-1] != yp):
      adjusts += 1;
      W = weightAdjustment(W, n, (row[-1] - yp), row[:-1])
      weights.append(W)
  return (adjusts, weights, W)



In [76]:
def perceptronLearning(inputData, W, maxEpoch, n):
  epochCount = 0
  adjustCount = 0
  adjust = True
  while((epochCount < maxEpoch) or adjust):
    epochCount += 1
    (numAdjusts, oldWeights, W) = epoch(inputData, W, n)
    print("\nNumero de epocas: " + str(epochCount))
    print("Numero de ajustes: " + str(numAdjusts))
    print("Pesos: ")
    for weight in oldWeights:
      print(weight)
    adjustCount += numAdjusts
    if(numAdjusts == 0):
      adjust = 0 #nao houve alteracoes nos valores dos pesos
  print("Numero total de ajustes: " + str(adjustCount))
  print("Pesos finais: ")
  print(W)
  return W


In [70]:
def addBias(inputData, bias):
  nd= np.insert(inputData, 2, bias, axis=1)
  return nd


In [71]:
n_DataAll = 0.1 # taxa de aprendizado
teta_DataAll = 0 #degrau
w_DataAll = np.random.uniform(-0.5, 0.5, 3) #min, max, numero_de_valores
print("Vetor de pesos iniciais: ")
print(w_DataAll)
data_All = addBias(data_All, 1)
print("\n\nDados de entrada com o vies: \n")
data_All

Vetor de pesos iniciais: 
[ 0.45810407  0.25968084 -0.39622453]


Dados de entrada com o vies: 



array([[-363.7884,  244.1423,    1.    ,    0.    ],
       [ 328.7572, -256.7658,    1.    ,    1.    ],
       [-164.9827,  613.2164,    1.    ,    0.    ],
       ...,
       [ 872.4311,  669.1192,    1.    ,    1.    ],
       [ 822.6894, -702.6489,    1.    ,    1.    ],
       [-140.147 ,  734.0983,    1.    ,    0.    ]])

In [78]:
perceptronLearning(data_All, w_DataAll, 0, n_DataAll)


Numero de epocas: 1
Numero de ajustes: 47
Pesos: 
[ 16.95637407 -61.06195916  -0.49622453]
[ 89.75239407 -25.23239916  -0.39622453]
[   6.22278407 -124.35822916   -0.49622453]
[  55.40964407 -107.72949916   -0.59622453]
[138.00834407 -27.87366916  -0.49622453]
[  97.99943407 -105.76635916   -0.59622453]
[147.46025407 -56.87230916  -0.69622453]
[ 107.91100407 -153.96634916   -0.79622453]
[200.15298407 -67.49377916  -0.89622453]
[188.25587407 -95.39331916  -0.99622453]
[ 160.04841407 -128.97743916   -1.09622453]
[  95.75920407 -197.04206916   -0.99622453]
[ 148.86352407 -161.26266916   -0.89622453]
[ 213.85468407 -100.37098916   -0.99622453]
[ 162.92110407 -163.77095916   -0.89622453]
[250.05586407 -77.08112916  -0.99622453]
[ 198.14053407 -133.28214916   -1.09622453]
[ 133.25450407 -207.89823916   -1.19622453]
[ 200.29215407 -157.73173916   -1.09622453]
[ 122.82920407 -255.71944916   -0.99622453]
[ 207.68008407 -194.44606916   -1.09622453]
[ 141.00525407 -264.34139916   -0.99622453]
[ 

array([ 337.40119407, -337.18281916,   -0.99622453])

In [ ]:
n = 0.1 #Taxa de aprendizado
teta = 0 #Degrau usado na função de ativação
w = np.random.uniform(-0.5, 0.5, (1, 3)) #Vetor de pesos inicial
print("Vetor inicial de pesos: {}\n".format(w[0]))
 
def funcao(u): #Função de ativação
  if(u >= teta):
    return 1
  else:
    return 0
 
i = 0
ult_indice = len(dados_All) - 1
encerrar = True
qtd_epocas = 0
total_ajustes = 0
 
while i <= ult_indice:
  
  if (i == 0): #Verifica a a quantidade de épocas
    qtd_epocas += 1
    print('Época: {}'.format(qtd_epocas))
  
  linha = dados_All[i]
  yd = linha[2]
  x = np.array([-1, linha[0], linha[1]])
 
  u = 0
  for j in range(3):
    u += (x[j] * w[-1][j])
 
  y = funcao(u) #Chama a função de ativação
  e = yd - y #Erro
 
  if (e != 0): #Há necessidade de aprendizagem
    print('Ajuste do peso: {} -> Exemplo: {}'.format(w[-1], i + 1))
    peso_novo = np.array([w[-1] + ((n * e) * x)]) #Delta
    w = np.append(w, peso_novo, axis=0) #Começa a próxima época
    encerrar = False
    total_ajustes += 1
 
  if (ult_indice == i): #Última linha
    print('Número de ajustes: {}'.format(total_ajustes))
    print('Vetor de pesos: ', w[-1])
    print('\n')
    if (encerrar == False):
      total_ajustes = 0
      encerrar = True
      i = -1 #Vai para o começo do array de dados
 
  i += 1
 
print('Total de ajustes: ', len(w) - 1)
print('Total de épocas: ', qtd_epocas)

Vetor inicial de pesos: [-0.01377581 -0.25390031 -0.20273453]

Época: 1
Ajuste do peso: [-0.01377581 -0.25390031 -0.20273453] -> Exemplo: 1
Ajuste do peso: [  0.08622419  36.12493969 -24.61696453] -> Exemplo: 4
Ajuste do peso: [   0.18622419  -17.53411031 -101.11271453] -> Exemplo: 8
Ajuste do peso: [  0.08622419  55.26190969 -65.28315453] -> Exemplo: 19
Ajuste do peso: [-1.37758150e-02  1.37860610e+02  1.45726755e+01] -> Exemplo: 27
Ajuste do peso: [ 8.62241850e-02  1.43706370e+02 -6.37219145e+01] -> Exemplo: 32
Ajuste do peso: [   0.18622419  103.69745969 -141.61460453] -> Exemplo: 44
Ajuste do peso: [  0.28622419 157.36726969 -92.52233453] -> Exemplo: 46
Ajuste do peso: [   0.18622419  104.40720969 -149.39179453] -> Exemplo: 48
Ajuste do peso: [  0.28622419 163.96672969 -99.26946453] -> Exemplo: 72
Ajuste do peso: [   0.18622419  118.44209969 -164.90539453] -> Exemplo: 108
Ajuste do peso: [  0.28622419 209.15795969 -90.19207453] -> Exemplo: 111
Ajuste do peso: [   0.18622419  151.37